swagger: "2.0"
info:
  description: "API HTTP (JSON) de e-commerce (venda online)"
  version: "1.0.0"
  title: "API de carrinho"
  contact:
    email: "rtakemura@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
- name: "products"
  description: "Operações de produto"
- name: "carts"
  description: "Operações de carrinho"
schemes:
- "http"
paths:
  /products:
    get:
      tags:
      - "products"
      summary: "Lista todos os produtos (menos brindes)"
      description: ""
      produces:
      - "application/json"
      responses:
        "200":
          description: "Operação realizada com sucesso"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"
  /products/{productId}:
    get:
      tags:
      - "products"
      summary: "Obtem as informações do produto pelo ID"
      parameters:
        - name: "productId"
          in: "path"
          description: "ID do produto"
          required: true
          type: "integer"
          format: "int32"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Operação realizada com sucesso"
          schema:
            $ref: "#/definitions/Product"
        "404":
          description: "Produto não encontrado"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Erro interno do servidor"
  /carts/checkout:
    post:
      tags:
      - "carts"
      summary: "Cria o carrinho de compras"
      description: ""
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Informações da compra"
        required: true
        schema:
          $ref: "#/definitions/CartRequest"
      responses:
        "201":
          description: "Operação realizada com sucesso"
          schema:
            $ref: "#/definitions/Cart"
        "404":
          description: "Produto não encontrado"
          schema:
            $ref: "#/definitions/Error"
        "400":
          description: "Estrutura inválida"
          schema:
            $ref: "#/definitions/Error"
        "422":
          description: "Valores inválidos"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Erro interno do servidor"
definitions:
  Product:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
        description: "ID do produto"
      title:
        type: "string"
        description: "Nome do produto"
      description:
        type: "string"
        description: "Descrição do produto"
      amount:
        type: "integer"
        format: "int32"
        description: "Preço do produto em centavos"
      is_gift:
        type: "boolean"
        description: "É brinde?"
        default: false
  CartItemRequest:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
        description: "ID do produto"
      quantity:
        type: "integer"
        format: "int32"
        description: "Quantidade"
  CartRequest:
    type: "object"
    properties:
      products:
        $ref: "#/definitions/CartItemRequest"
  CartItem:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
        description: "ID do produto"
      quantity:
        type: "integer"
        format: "int32"
        description: "Quantidade"
      unit_amount:
        type: "integer"
        format: "int32"
        description: "Preço do produto em centavos"
      total_amount:
        type: "integer"
        format: "int32"
        description: "Valor total na compra desse produto em centavos"
      discount:
        type: "integer"
        format: "int32"
        description: "Valor total de desconto em centavos"
      is_gift:
        type: "boolean"
        description: "É brinde?"
        default: false
  Cart:
    type: "object"
    properties:
      total_amount:
        type: "integer"
        format: "int32"
        description: "Valor total da compra sem desconto"
      total_amount_with_discount:
        type: "integer"
        format: "int32"
        description: "Valor total da compra sem desconto"
      total_discount:
        type: "integer"
        format: "int32"
        description: "Valor total da compra sem desconto"
      products:
        $ref: "#/definitions/CartItem"
  Error:
    type: "object"
    properties:
      code:
        type: "string"
        description: "Código de erro"
      message:
        type: "string"
        description: "Mensagem de erro"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"